name: Push to docker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_API_KEY }} | docker login -u whynotjava --password-stdin

      - name: Build image
        run: docker build -t whynotjava/domaincheckapi-docker .

      - name: Push to docker hub
        run: docker push whynotjava/domaincheckapi-docker
